
dist: trusty
sudo: false

language: node_js
node_js:
  - '11.0'
branches:
  only:
    - master
cache:
  directories:
    - ./node_modules
before_script:
  - npm install -g @angular/cli
install:
  - npm install

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//03tc3wmH3ol4kCgYIARAAGAMSNwF-L9IrE43hcPEsRuyGYJmwiv8re-FMiS5kC7XeTvNAWHLwD47TWqZPBjbLjlQPnIiJn8cCi7c"
  project: "dev2"
